from __future__ import annotations

CVE_RULES = [
    {
        "id": "CVE-2011-2523",
        "title": "Potential vsftpd backdoor exposure",
        "service": "ftp",
        "product_contains": "vsftpd",
        "version_equals": "2.3.4",
        "severity": "critical",
        "description": "The detected vsftpd version matches a release historically associated with a backdoored build.",
        "recommendation": "Upgrade to a trusted vsftpd release from a verified source and validate package integrity.",
    },
    {
        "id": "CVE-2021-41773",
        "title": "Potential Apache path traversal exposure",
        "service": "http",
        "product_contains": "apache httpd",
        "version_in": {"2.4.49", "2.4.50"},
        "severity": "high",
        "description": "The detected Apache HTTP Server version matches a release associated with path traversal vulnerabilities.",
        "recommendation": "Upgrade Apache HTTP Server to a patched release and verify path normalization protections.",
    },
    {
        "id": "CVE-2014-0160",
        "title": "Potential OpenSSL Heartbleed exposure",
        "service": "ssl",
        "product_contains": "openssl",
        "version_contains": "1.0.1",
        "severity": "critical",
        "description": "The detected OpenSSL version string suggests a potentially Heartbleed-affected release family.",
        "recommendation": "Upgrade OpenSSL immediately and rotate any affected secrets and certificates.",
    },
    {
        "id": "CVE-2019-10149",
        "title": "Potential Exim remote code execution exposure",
        "service": "smtp",
        "product_contains": "exim",
        "version_lt": "4.92",
        "severity": "high",
        "description": "The detected Exim version may fall in a release range associated with a critical remote code execution issue.",
        "recommendation": "Upgrade Exim to a patched version and review mail relay exposure.",
    },
    {
        "id": "CVE-2018-15473",
        "title": "Potential OpenSSH username enumeration exposure",
        "service": "ssh",
        "product_contains": "openssh",
        "version_lt": "7.7",
        "severity": "medium",
        "description": "The detected OpenSSH version may fall in a range historically associated with username enumeration behavior.",
        "recommendation": "Upgrade OpenSSH to a patched release and limit internet exposure where possible.",
    },
    {
        "id": "CVE-2020-14145",
        "title": "Potential ProFTPD mod_copy exposure",
        "service": "ftp",
        "product_contains": "proftpd",
        "version_equals": "1.3.3c",
        "severity": "high",
        "description": "The detected ProFTPD version matches a release family historically associated with mod_copy abuse.",
        "recommendation": "Upgrade ProFTPD to a patched release and review enabled modules against vendor guidance.",
    },
    {
        "id": "CVE-2020-1938",
        "title": "Potential Apache Tomcat Ghostcat exposure",
        "service": "http",
        "product_contains": "apache tomcat",
        "version_lt": "9.0.31",
        "severity": "high",
        "description": "The detected Apache Tomcat version may fall in a release range associated with the Ghostcat vulnerability.",
        "recommendation": "Upgrade Tomcat to a patched version and restrict AJP exposure if enabled.",
    },
    {
        "id": "CVE-2022-3602",
        "title": "Potential OpenSSL X.509 email address buffer overflow exposure",
        "service": "ssl",
        "product_contains": "openssl",
        "version_in": {"3.0.0", "3.0.1", "3.0.2", "3.0.3", "3.0.4", "3.0.5", "3.0.6"},
        "severity": "high",
        "description": "The detected OpenSSL version matches releases associated with a high-profile X.509 parsing vulnerability.",
        "recommendation": "Upgrade OpenSSL to a patched release and validate dependent services after patching.",
    },
    {
        "id": "CVE-2017-7269",
        "title": "Potential Microsoft IIS WebDAV buffer overflow exposure",
        "service": "http",
        "product_contains": "iis",
        "version_contains": "6.0",
        "severity": "high",
        "description": "The detected IIS version matches a legacy release family associated with a WebDAV buffer overflow vulnerability.",
        "recommendation": "Retire or patch the affected IIS deployment and disable WebDAV if it is not required.",
    },
    {
        "id": "CVE-2017-7494",
        "title": "Potential Samba remote code execution exposure",
        "product_contains": "samba",
        "version_lt": "4.6.4",
        "severity": "high",
        "description": "The detected Samba version may fall in a release range associated with a remote code execution vulnerability.",
        "recommendation": "Upgrade Samba to a patched release and restrict SMB exposure to trusted networks.",
    },
    {
        "id": "CVE-2022-1388",
        "title": "Potential F5 BIG-IP management exposure",
        "service": "http",
        "product_contains": "big-ip",
        "version_in": {"16.1.2.2", "15.1.5.1", "14.1.4.6", "13.1.3.6", "12.1.6"},
        "severity": "critical",
        "description": "The detected BIG-IP version matches releases associated with a critical management interface vulnerability.",
        "recommendation": "Patch the BIG-IP device immediately and restrict management interfaces to trusted administrative networks.",
    },
    {
        "id": "CVE-2019-19781",
        "title": "Potential Citrix ADC path traversal exposure",
        "service": "http",
        "product_contains": "citrix adc",
        "version_lt": "13.0.47.24",
        "severity": "critical",
        "description": "The detected Citrix ADC version may fall in a release family associated with critical path traversal and code execution issues.",
        "recommendation": "Upgrade Citrix ADC to a patched release and verify management surface restrictions.",
    },
]
